apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-170185430
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-170185430
    app.kubernetes.io/part-of: test-app-170185430
  name: java-quarkus-170185430
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-170185430
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-170185430
    spec:
      containers:
      - image: quay.io/hacdev/fndgmbcy-tenant/test-app-170185430/java-quarkus-170185430@sha256:fbd3e33f17bd51dbeca846a6be48eea58887d5304f0abc50121adcad62b5aade
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
